// <auto-generated />
namespace LMDB.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initg));
        
        string IMigrationMetadata.Id
        {
            get { return "201704132152547_Init-g"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
